version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: prod-mysql
    restart: always
    env_file:
      - ./project/backend/.env
    environment:
      TZ: Asia/Tokyo
    ports:
      - "3306:3306"
    volumes:
      - ./project/initdb/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/mysql
    healthcheck:
      test: [
        "CMD-SHELL",
        "mysqladmin ping -u root -p$$MYSQL_ROOT_PASSWORD"
      ]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - app-network

  redis:
    image: redis:7.2
    container_name: prod-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network

  backend:
    build:
      context: ./project/backend
      dockerfile: Dockerfile
    container_name: prod-backend
    env_file:
      - ./project/backend/.env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: "always"
    ports:
      - "8000:8000"
    networks:
      - app-network

  frontend:
    build:
      context: ./project/frontend
      dockerfile: Dockerfile
    container_name: prod-frontend
    env_file:
      - ./project/frontend/.env
    depends_on:
      - backend
    networks:
      - app-network

  nginx:
    image: nginx:1.25
    container_name: prod-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./project/frontend/build:/usr/share/nginx/html:ro
      - ./nginx/certbot/www:/var/www/certbot
      - ./nginx/certbot/conf:/etc/letsencrypt
    depends_on:
      frontend:
        condition: service_started
      backend:
        condition: service_healthy
    networks:
      - app-network 

volumes:
  db_data:
  redis_data:

networks:
  app-network:
